# this workflow trigger conversion of dsupdt.usg, if it is changed, into section*.rst in repository
# NCAR/gdex-docs-dsupdt
#
on:
  pull_request:
    paths:
      - 'src/rda_python_dsupdt/dsupdt.usg'

jobs:
  trigger_conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DSUPDT_USG }}
          repository: NCAR/gdex-docs-dsupdt
          event-type: trigger-conversion
          client-payload: '{"branch":"${{ github.event.pull_request.head.ref }}"}'
          
